﻿$lines = @(
    'package com.example.rocketmq.controller;',
    '',
    'import dto.org.tech.rocketmq.MessageRequest;',
    'import dto.org.tech.rocketmq.MessageResponse;',
    'import entity.org.tech.rocketmq.MessageRecord;',
    'import repository.org.tech.rocketmq.MessageRecordRepository;',
    'import service.org.tech.rocketmq.ProducerService;',
    'import org.apache.rocketmq.spring.core.RocketMQTemplate;',
    'import org.slf4j.Logger;',
    'import org.slf4j.LoggerFactory;',
    'import org.springframework.beans.factory.annotation.Autowired;',
    'import org.springframework.http.ResponseEntity;',
    'import org.springframework.web.bind.annotation.*;',
    '',
    'import java.util.HashMap;',
    'import java.util.List;',
    'import java.util.Map;',
    'import java.util.UUID;',
    'import java.util.stream.Collectors;',
    '',
    '@RestController',
    '@RequestMapping("/api/message")',
    'public class MessageController {',
    '',
    '    private static final Logger logger = LoggerFactory.getLogger(MessageController.class);',
    '',
    '    @Autowired',
    '    private ProducerService producerService;',
    '',
    '    @Autowired',
    '    private RocketMQTemplate rocketMQTemplate;',
    '',
    '    @Autowired',
    '    private MessageRecordRepository messageRecordRepository;',
    '',
    '    @PostMapping("/sync")',
    '    public ResponseEntity<Map<String, Object>> sendSyncMessage(@RequestBody MessageRequest request) {',
    '        logger.info("send sync: {}", request);',
    '        String messageId = producerService.sendSyncMessage(request);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("messageId", messageId);',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "sync message sent");',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @PostMapping("/async")',
    '    public ResponseEntity<Map<String, Object>> sendAsyncMessage(@RequestBody MessageRequest request) {',
    '        logger.info("send async: {}", request);',
    '        String messageId = producerService.sendAsyncMessage(request);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("messageId", messageId);',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "async message sent");',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @PostMapping("/oneway")',
    '    public ResponseEntity<Map<String, Object>> sendOnewayMessage(@RequestBody MessageRequest request) {',
    '        logger.info("send oneway: {}", request);',
    '        String messageId = producerService.sendOnewayMessage(request);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("messageId", messageId);',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "oneway message sent");',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @PostMapping("/delay")',
    '    public ResponseEntity<Map<String, Object>> sendDelayMessage(@RequestBody MessageRequest request, @RequestParam(defaultValue = "30") int delaySeconds) {',
    '        logger.info("send delay: {}, delay: {}s", request, delaySeconds);',
    '        String messageId = producerService.sendDelayMessage(request, delaySeconds);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("messageId", messageId);',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "delay message sent");',
    '        response.put("delaySeconds", delaySeconds);',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @PostMapping("/orderly")',
    '    public ResponseEntity<Map<String, Object>> sendOrderlyMessage(@RequestBody MessageRequest request, @RequestParam(defaultValue = "default") String shardingKey) {',
    '        logger.info("send orderly: {}, shardingKey: {}", request, shardingKey);',
    '        String messageId = producerService.sendOrderlyMessage(request, shardingKey);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("messageId", messageId);',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "orderly message sent");',
    '        response.put("shardingKey", shardingKey);',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @PostMapping("/batch")',
    '    public ResponseEntity<Map<String, Object>> sendBatchMessage(@RequestParam String topic, @RequestBody List<String> contents) {',
    '        logger.info("send batch: topic={}, count={}", topic, contents.size());',
    '        producerService.sendBatchMessage(topic, contents);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "batch message sent");',
    '        response.put("count", contents.size());',
    '        response.put("topic", topic);',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @PostMapping("/transaction")',
    '    public ResponseEntity<Map<String, Object>> sendTransactionMessage(@RequestBody MessageRequest request) {',
    '        logger.info("send transaction: {}", request);',
    '        String messageId = UUID.randomUUID().toString();',
    '        String body = String.format("{\"messageId\":\"%s\",\"content\":\"%s\",\"messageType\":\"TRANSACTION\"}", messageId, request.getContent());',
    '        org.apache.rocketmq.common.message.Message m = new org.apache.rocketmq.common.message.Message("transaction-topic", request.getTags(), messageId, body.getBytes(java.nio.charset.StandardCharsets.UTF_8));',
    '        rocketMQTemplate.sendMessageInTransaction("demo-transaction-producer-group", "transaction-topic", m, null);',
    '        Map<String, Object> response = new HashMap<>();',
    '        response.put("messageId", messageId);',
    '        response.put("status", "SUCCESS");',
    '        response.put("message", "transaction message sent");',
    '        return ResponseEntity.ok(response);',
    '    }',
    '',
    '    @GetMapping("/{messageId}")',
    '    public ResponseEntity<MessageResponse> getMessageById(@PathVariable String messageId) {',
    '        return messageRecordRepository.findByMessageId(messageId).map(this::convertToResponse).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());',
    '    }',
    '',
    '    @GetMapping("/list")',
    '    public ResponseEntity<List<MessageResponse>> getAllMessages() {',
    '        List<MessageResponse> messages = messageRecordRepository.findAll().stream().map(this::convertToResponse).collect(Collectors.toList());',
    '        return ResponseEntity.ok(messages);',
    '    }',
    '',
    '    @GetMapping("/status/{status}")',
    '    public ResponseEntity<List<MessageResponse>> getMessagesByStatus(@PathVariable String status) {',
    '        List<MessageResponse> messages = messageRecordRepository.findByStatus(status).stream().map(this::convertToResponse).collect(Collectors.toList());',
    '        return ResponseEntity.ok(messages);',
    '    }',
    '',
    '    @DeleteMapping("/{messageId}")',
    '    public ResponseEntity<Map<String, Object>> deleteMessage(@PathVariable String messageId) {',
    '        return messageRecordRepository.findByMessageId(messageId).map(record -> {',
    '            messageRecordRepository.delete(record);',
    '            Map<String, Object> response = new HashMap<>();',
    '            response.put("status", "SUCCESS");',
    '            response.put("message", "message deleted");',
    '            return ResponseEntity.ok(response);',
    '        }).orElse(ResponseEntity.notFound().build());',
    '    }',
    '',
    '    private MessageResponse convertToResponse(MessageRecord record) {',
    '        MessageResponse response = new MessageResponse();',
    '        response.setId(record.getId());',
    '        response.setMessageId(record.getMessageId());',
    '        response.setTopic(record.getTopic());',
    '        response.setMessageType(record.getMessageType());',
    '        response.setContent(record.getContent());',
    '        response.setStatus(record.getStatus());',
    '        response.setCreateTime(record.getCreateTime());',
    '        response.setUpdateTime(record.getUpdateTime());',
    '        return response;',
    '    }',
    '}'
)
[System.IO.File]::WriteAllLines('d:\workspace\workspace_tech_yushen1202\tech-mq-rocketmq\rocketmq-demo\src\main\java\com\example\rocketmq\controller\MessageController.java', $lines, [System.Text.Encoding]::UTF8)
Write-Host 'Created Controller'